config/routes.rb
Rails.application.routes.draw do
  get "/auth/oauth2/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"
  get "/logout" => "logout#logout"
  get "/reviews" => "reviews#index"
  
  root "vehicles#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :vehicles, only: [:index] do
    resources :reviews, except: :show
  end
  resources :home, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :vehicle
  validates :rating, presence: true, inclusion: {in: 1..5}
  validates :vehicle_id, presence: true
  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }

  def current_users? (email)
    if email == self.email
      return true
    else
      return false
    end
  end
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :vehicle_size
  has_many :reviews
  
  validates_presence_of :vehicle_size, :make, :model, :year, :vin, :color
  validates :vin, length: {maximum: 17, minimum: 17}
end

app/models/vehicle_size.rb
class VehicleSize < ApplicationRecord
    has_many :vehicles

    validates :name, uniqueness: true
    validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include ApplicationHelper
end

app/controllers/auth0_controller.rb
class Auth0Controller < ApplicationController
  def callback
    # This stores all the user information that came from Auth0
    # and the IdP
    session[:userinfo] = request.env['omniauth.auth']

    # Redirect to the URL you want after successful auth
    redirect_to root_url
  end

  def failure
    # show a failure page or redirect to an error page
    @error_msg = request.params['message']
  end
end

app/controllers/concerns/secured.rb
module Secured
  extend ActiveSupport::Concern

  included do
    before_action :logged_in_using_omniauth?
  end

  def logged_in_using_omniauth?
    redirect_to '/auth/auth0' unless session[:userinfo].present?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/logout_controller.rb
class LogoutController < ApplicationController
    include LogoutHelper

    def logout
        reset_session
        redirect_to logout_url.to_s
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    include Secured
    skip_before_action :logged_in_using_omniauth?, only: [:index]
    def index
        @user_reviews = []
        user_email = ''
        if logged_in?
            user_email = session[:userinfo]['info']['name']
        end
        if params[:vehicle_id] && logged_in?
            @vehicle = Vehicle.find(params[:vehicle_id])
            @user_reviews = Review.where({vehicle_id: params[:vehicle_id], email: user_email})
            @reviews = Review.where('vehicle_id = ? AND email != ?', params[:vehicle_id], user_email)
        elsif params[:vehicle_id]
            @reviews = Review.where(vehicle_id: params[:vehicle_id])
        elsif logged_in?
            @user_reviews = Review.where({email: user_email})
            @reviews = Review.where('email != ?', user_email)
        else
            @reviews = Review.all
        end
    end
    
    def new
        @vehicle = Vehicle.find(params[:vehicle_id])
        @review = Review.new()
    end
    def create
        @vehicle = Vehicle.find(params[:vehicle_id])
        @review = Review.new(review_params)
        @review.email = session[:userinfo]["info"]["name"]
        if @review.save
            redirect_to vehicle_reviews_path(@vehicle)
        else
            render :new
        end
    end
    
    def edit
        @vehicle = Vehicle.find(params[:vehicle_id])
        @review = Review.find(params[:id])
    end
    def update
        @vehicle = Vehicle.find(params[:vehicle_id])
        @review = Review.find(params[:id])
        if @review.update(review_params)
            redirect_to vehicle_reviews_path(@vehicle)
        else 
            render :edit
        end
    end
    
    def destroy
        @vehicle = Vehicle.find(params[:vehicle_id])
        @review = Review.find(params[:id])
        if @review.destroy
            redirect_to vehicle_reviews_path(@vehicle)
        else
            render :index
        end
    end
    private

    def review_params
        params.permit(:comment, :rating, :vehicle_id)
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
    def index
        
        if request.xhr?
            if params[:search_string] == 'size'
                params[:search_string] = 'vehicle_size_id'
            end

            if params[:backwards] == "true"
                @vehicles = Vehicle.order(params[:search_string] => :desc)
            else 
                @vehicles = Vehicle.order(params[:search_string])
            end
            render partial: 'vehicles/partials/vehicle_rows', locals: {vehicles: @vehicles}
            
        else
            @vehicles = Vehicle.order(:make)
        end
    end

    def new
        @vehicle = Vehicle.new
    end

    def create
        @vehicle = Vehicle.new(vehicle_params)
        if @vehicle.save
            redirect_to @vehicle
        else
            render 'new'
        end
    end

    def edit
        @vehicle = Vehicle.find(params[:id])
    end

    def update
        @vehicle = Vehicle.find(params[:id])
        @vehicle.update(vehicle_params)
        redirect_to vehicle_path(@vehicle)
    end


    def destroy
        @vehicle = Vehicle.find(params[:id])
        @vehicle.destroy
        redirect_to vehicles_path
    end

    private

    def vehicle_params
        params.require(:vehicle).permit(:make, :model, :vin, :year, :vehicle_size_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include SessionHelper
end

app/helpers/logout_helper.rb
module LogoutHelper
    def logout_url
        domain = Rails.application.secrets.auth0_domain
        client_id = Rails.application.secrets.auth0_id
        request_params = {
            returnTo: root_url,
            client_id: client_id
        }

        URI::HTTPS.build(host: domain, path: '/logout', query: to_query(request_params))
    end

    def to_query(hash)
        hash.map { |k, v| "#{k}=#{URI.escape(v)}" unless v.nil? }.reject(&:nil?).join('&')
    end

end

app/helpers/session_helper.rb
module SessionHelper
  def get_state
    state = SecureRandom.hex(24)
    session['omniauth.state'] = state

    state
  end

  def logged_in?
    return session[:userinfo].present?
  end

  def user_email
    return session[:userinfo]['info']['name']
  end
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>We Review cars with a passion</title>
    <%= csrf_meta_tags %>
    <%# jquery %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <%# star ratings %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.css">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.js"></script>

    <%# fixed table headers %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/floatthead/2.1.1/jquery.floatThead.min.js"></script>

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="navbar-fixed">
      <nav class="indigo lighten-1">
        <div class="nav-wrapper">
          <a class="brand-logo left" href="/">Car Sham</a>
          <ul id="nav-mobile" class="right">
            <li><%= link_to 'Reviews', reviews_path(vehicle_id: nil) %></li>
            <li><a href="/vehicles">Vehicles</a></li>
            <% if logged_in?() %>
              <li><a href="/logout">Logout</a></li>
            <% else %>
              <li><a href="/auth/auth0">Login / Register</a></li>
            <% end %>
          </ul>


        </div>
      </nav>
    </div>
    <%= yield %>
  </body>
</html>

app/views/reviews/edit.html.erb
<br>
<br>
<br>
<div class='row'>
    <%= form_tag vehicle_review_path(@vehicle, @review), method: :put, class: 'col s8 offset-s2 review-form z-depth-5 teal-text text-lighten-2' do %>
        <div class='row center-align'>
            <div class='input-field col s12'>
                <div class=''><h5>Rating*</h5></div>
                <div class="review-rating-new rateYo-centered" value="<%= @review.rating %>"></div>
                <%= hidden_field_tag 'rating', @review.rating %>
            </div>
            <div class='input-field col s12'>
                <div class=''><h5>Comment</h5></div>
                <%= text_area_tag 'comment', @review.comment , class: 'materialize-textarea' %>
            </div>
            <div class='input-field col s12 required-explain'>
                <i>*Required</i>
            </div>
            <div class='input-field col s12'>
                <%= button_tag sanitize('<i class="material-icons right">send</i>' + "Submit"), class: 'btn waves-effect waves-light' %>
            </div>
            
        </div>
    <% end %>
    
</div>
<script>
    loadRatings();
</script>

app/views/reviews/index.html.erb
<%# if !@user_reviews && !@reviews %>

<%# end %>

<div class='center-align'>
    <% if @user_reviews.empty? && @user_reviews.empty? && @reviews.empty?%>
        <% if @vehicle %>
            <h4>Be the first to Review this car!</h4>
            <% if logged_in?() %>
                <%= link_to 'Add Review', new_vehicle_review_path(@vehicle), class: 'waves-effect waves-light btn' %>
            <% else %>
                <p>Please log in to do so.</p>
            <% end %>
        <% else %>
            <h4>There are no reviews existing in the database</h4>
            <p>Why dont you leave one <%= link_to 'here', vehicles_path %></p>
        <% end %>
    <% end %>
</div>
<table class="review-table">
    <% if !@user_reviews.empty? %>
            <thead>
                <tr>
                    <td colspan=5>
                        <div class="center-align">
                        
                            <h1>Your Reviews<h1>
                            
                            <% if @vehicle%>
                                <%= link_to 'Add Review', new_vehicle_review_path(@vehicle), class: 'waves-effect waves-light btn' %>
                            <% end %>
                        </div>
                    </td>
                </tr>
                <tr>
                    <th></th>
                    <th>Rating</th>
                    <th>User</th>
                    <th>VIN</th>
                    <th>Created</th>
                </tr>
            </thead>
            <tbody class="collection review-table-body">
                <%= render partial: 'reviews/partials/review_rows', locals: {reviews: @user_reviews} %>
            </tbody>
    <% end %>
    <% if !@reviews.empty? %>
        <%# <tbody class="collection review-table-body">
            <tr class="review-bot review-item">
                
            </tr>
        </tbody> %>
            <thead>
                <tr>
                    <td colspan=5>
                        <div class="col s12 center-align">
                            <h1>All Reviews<h1>
                            <% if @vehicle && @user_reviews.empty? %>
                                <%= link_to 'Add Review', new_vehicle_review_path(@vehicle), class: 'waves-effect waves-light btn' %>
                            <% end %>
                        </div>
                    </td>
                </tr>
                <tr>
                    <th></th>
                    <th>Rating</th>
                    <th>User</th>
                    <th>VIN</th>
                    <th>Created</th>
                </tr>
            </thead>
            <tbody class="collection review-table-body">
                <%= render partial: 'reviews/partials/review_rows', locals: {reviews: @reviews} %>
            </tbody>
    <% end %>
</table>

<script>
    loadRatings();
</script>

app/views/reviews/new.html.erb
<br>
<br>
<br>
<div class='row'>
    <%= form_tag vehicle_reviews_path(@vehicle), method: :post, class: 'col s8 offset-s2 review-form z-depth-5 teal-text text-lighten-2' do %>
        <div class='row center-align'>
            <div class='input-field col s12'>
                <div class=''><h5>Rating*</h5></div>
                <div class="review-rating-new rateYo-centered" value="5"></div>
                <%= hidden_field_tag 'rating' %>
            </div>
            <div class='input-field col s12'>
                <div class=''><h5>Comment</h5></div>
                <%= text_area_tag 'comment', nil, class: 'materialize-textarea' %>
            </div>
            <div class='input-field col s12 required-explain'>
                <i>*Required</i>
            </div>
            <div class='input-field col s12'>
                <%= button_tag sanitize('<i class="material-icons right">send</i>' + "Submit"), class: 'btn waves-effect waves-light' %>
            </div>
            
        </div>
    <% end %>
    
</div>
<script>
    loadRatings();
</script>

app/views/reviews/partials/_review_rows.html.erb
<% reviews.each do |r| %>
        
        <tr id="review--<%=r.id%>" class="review-item">
            <td><div class="valign-wrapper"><%= r.comment.presence ? sanitize('<i class="material-icons details-down">details</i>') : '' %></div></td>
            <td><div class="review-rating-ue" value="<%= r.rating %>"></div></td>
            <td><div><%= r.email %></div></td>
            <td><div><%= r.vehicle.vin %></div></td>
            <td><div><%= r.created_at.strftime("%m-%d-%Y") %></div></td>
        </tr>
        <tr class="review-bot review-item">
            <td colspan=5>
                
                <% if r.comment.presence %>
                    <div id="review-details--<%=r.id%>" class="hide review-item-details">
                        <div class='row'>
                            <div class='col s6 vehicle-info'>
                                <div class='row'>
                                    <div class='col s6'>
                                    <% p r %>
                                        Make: <%= r.vehicle.make %>
                                    </div>    
                                    <div class='col s6'>
                                        Model: <%= r.vehicle.model %>
                                    </div>    
                                </div>    
                                <div class='row'>
                                    <div class='col s6'>
                                        Year: <%= r.vehicle.year %>
                                    </div>    
                                    <div class='col s6'>
                                        Color: <%= r.vehicle.color %>
                                    </div>    
                                </div>    
                            </div>    
                            <div class='col s6'>
                                <div class='row'>
                                    <div class='col s12'>
                                        Comment:
                                    </div>    
                                </div>
                                <div class='row'>
                                    <div class='col s12'>
                                        <%= r.comment %>        
                                    </div>    
                                </div>    
                            </div>
                            <% if logged_in? && r.current_users?(user_email) %>
                                <div class='col s6'>
                                    <%= link_to sanitize('<i class="material-icons right">send</i>' + "Edit"), edit_vehicle_review_path(r.vehicle, r), class: 'btn waves-effect waves-light full-btn' %>
                                </div>
                                <div class='col s6'>
                                    <%= link_to sanitize('<i class="material-icons right">delete</i>' + "Delete"), vehicle_review_path(r.vehicle, r), class: 'btn waves-effect waves-light full-btn red darken-2', method: :delete %>
                                </div>
                            <% end %>
                        </div>
                    </div>
                <% end %>
            </td>
        </tr>
<% end %>

app/views/vehicles/index.html.erb
<div style="width:100%;">
    <table class="centered highlight vehicle-table">
        <thead class="v-headers">
            <tr>
                <th value="make">Make<span class="v-sort-info"><i class="material-icons inline-icon">arrow_drop_down</i></span></th>
                <th value="model">Model<span class="v-sort-info"></span></th>
                <th value="year">Year<span class="v-sort-info"></span></th>
                <th value="size">Size<span class="v-sort-info"></span></th>
                <th value="vin">VIN<span class="v-sort-info"></span></th>
                <th>Review</th>
            </tr>
        </thead>

        <tbody class="v-container">
            <%= render partial: 'vehicles/partials/vehicle_rows', locals: {vehicles: @vehicles} %>
        </tbody>
    </div>
</div>

app/views/vehicles/partials/_vehicle_rows.html.erb
<% vehicles.each do |v| %>
    <tr>
        <td><%= v.make %></td>
        <td><%= v.model %></td>
        <td><%= v.year %></td>
        <td><%= v.vehicle_size.name %></td>
        <td><%= v.vin %></td>
        <%#  %>
        <td>
            <%= link_to vehicle_reviews_path(v), class: 'btn-floating btn-small waves-effect waves-light orange' do %>
                <i class='material-icons'>add</i>
            <% end %>
        </td>
    </tr>
<% end %>